apps:
  vs-code: false
  gimp: false
  chrome: false
  gnome-tweaks: false
  gnome-shell-extensions: false
  caffeine: false
  zsh: false
  spotify: false
  insomnia: false
  slack: false
  # VSCode recommended extensions
  vscode-eslint: false
  vscode-better-comments: false
  vscode-jsx-html-tags: false
  vscode-turbo-console-log: false
  vscode-markdownlint: false
  vscode-gitlens: false
  vscode-editor-config: false
  vscode-prettier: false
  vscode-auto-close-tag: false
  vscode-shell-format: false
  vscode-todo-tree: false
  vscode-env: false
  vscode-liveshare: false
  vscode-color-highlight: false
  vscode-material-icon-theme: false
  vscode-prisma: false
  vscode-liveserver: false
  vscode-omni: false
  vscode-javascript-booster: false
  vscode-css-auto-prefix: false
  vscode-auto-import: false
  vscode-styled-componets: false
  vscode-sass: false
  vscode-highlight-matching-tag: false
  vscode-mdx: false
